/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 money.gltf --transform
Author: Nick Sklias (https://sketchfab.com/NickSklias)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2-sided-100-us-dollar-bill-circa-2009-49f31b8a421c4da1b9043fc53c9a5eb0
Title: (2-sided) $100 US Dollar Bill (Circa 2009)
*/

// import React, { useRef } from 'react'
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/money-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={40}
      />
    </group>
  );
}

useGLTF.preload("/money-transformed.glb");
